apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  labels:
    app: mongo
spec:
  clusterIP: None  # 👈 Headless !
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
